In [60]:
import sqlite3
import pandas as pd

con=sqlite3.connect(r'C:\Users\muham\OneDrive\Desktop\Proj_3.1\Data\Raw\ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [61]:
def run_sql_file(path):
    with open(path,'r') as f:
        script =f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [62]:
q("""
    -- what is the strike rate of every batter in the death overs

    select batter,round(100.0*sum(batter_runs)/sum(
      CASE
        when is_wide_ball=0 AND is_no_ball=0
        then 1
        else 0
      END ),2)as strike_rate

from deliveries
where over_number>=15 AND is_super_over=0
group by batter
order by strike_rate desc;
    """)

             batter  strike_rate
0          WG Jacks       483.33
1          DT Patil       400.00
2        KT Maphaka       400.00
3            L Wood       300.00
4          PA Reddy       300.00
..              ...          ...
637     Sunny Gupta         0.00
638          U Kaul         0.00
639  V Pratap Singh         0.00
640   Y Prithvi Raj         0.00
641      YA Abdulla         0.00

[642 rows x 2 columns]

In [63]:
run_sql_file(r'C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\09_analysis_views.sql')

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\09_analysis_views.sql

In [64]:
q(""" select *
from v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [65]:
q("""select phase, count(*) from v_ball group by phase;""")

       phase  count(*)
0      Death     65488
1     Middle    132173
2  Powerplay     90390

In [66]:
q("""select count(*) from v_match_totals;""")

   count(*)
0      1187

In [67]:
q("""select count(*) from v_innings;""")

   count(*)
0      2418

In [68]:
q(""" select phase, count(*) from v_ball;""")

       phase  count(*)
0  Powerplay    288051

In [69]:
q("""select * from v_ball""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [70]:
q("""
    select
        batter,
        sum(is_legal) as balls,
        sum(batter_runs) as runs,
        round(100.0 * sum(batter_runs) / sum(is_legal), 2) as run_rate
    from v_ball
    where phase = 'Middle'
    group by batter
    having balls > 500
    order by run_rate desc
    limit 20;

""")

             batter  balls  runs  run_rate
0          V Sehwag    611  1062    173.81
1        RM Patidar    566   970    171.38
2          N Pooran    848  1351    159.32
3         H Klaasen    697  1099    157.68
4          CH Gayle   1285  2011    156.50
5        AD Russell    767  1182    154.11
6         SR Watson   1302  2006    154.07
7        GJ Maxwell   1163  1780    153.05
8          SE Marsh    971  1448    149.12
9          DR Smith    675  1004    148.74
10  B Sai Sudharsan    694  1031    148.56
11       JC Buttler   1303  1890    145.05
12         SA Yadav   1845  2664    144.39
13     Shubman Gill   1300  1864    143.38
14       RD Gaikwad    780  1093    140.13
15       MA Agarwal    781  1094    140.08
16          VR Iyer    524   731    139.50
17      YBK Jaiswal    582   811    139.35
18     Ishan Kishan   1091  1518    139.14
19         KL Rahul   1740  2412    138.62

In [71]:
q("""
--find a finisher:  highest strake rate in the last five overs.
select  batter,
        sum(is_legal)as balls,
        sum(batter_runs)as runs,
        round(100.0* sum(batter_runs)/ sum(is_legal), 2)as strike_rate
    from v_ball
    where phase = 'Death'
    group by batter
    having balls >500
    order by strike_rate desc
    limit 20;
""")

            batter  balls  runs  strike_rate
0   AB de Villiers    829  1868       225.33
1          RR Pant    513  1035       201.75
2       AD Russell    724  1432       197.79
3          V Kohli    807  1525       188.97
4       MP Stoinis    521   962       184.64
5        RG Sharma    837  1527       182.44
6         KL Rahul    502   907       180.68
7         MS Dhoni   1965  3468       176.49
8         DJ Bravo    516   909       176.16
9       KD Karthik   1091  1904       174.52
10       DA Miller    835  1454       174.13
11      SO Hetmyer    553   956       172.88
12        SK Raina    521   899       172.55
13       HH Pandya    870  1499       172.30
14      KA Pollard   1180  2032       172.20
15       JP Duminy    516   882       170.93
16       AT Rayudu    692  1179       170.38
17       YK Pathan    696  1126       161.78
18        AR Patel    629   971       154.37
19       RA Jadeja   1240  1882       151.77

In [72]:
q("""
--find a powerplay opener  who attacks from ball one.
select  batter,
        sum(is_legal)as balls,
        sum(batter_runs)as runs,
        round(100.0* sum(batter_runs)/ sum(is_legal), 2)as strike_rate
    from v_ball
    where phase = 'Powerplay'
    group by batter
    having balls >500
    order by strike_rate desc
    limit 10;
""")

            batter  balls  runs  strike_rate
0  Abhishek Sharma    744  1287       172.98
1        SP Narine    688  1174       170.64
2      YBK Jaiswal    984  1579       160.47
3   P Simran Singh    687  1070       155.75
4      JM Bairstow    623   944       151.52
5          PP Shaw    917  1347       146.89
6         V Sehwag   1096  1593       145.35
7          CA Lynn    537   779       145.07
8       JC Buttler   1257  1789       142.32
9      RA Tripathi    721  1013       140.50

In [73]:
q("""
--who is the most reliable in a chase - strike rate batting second?

select
     batter,
     sum(is_legal)as balls,
     sum(batter_runs)as runs,
     round(100.0* sum(batter_runs)/sum(is_legal),2) as strike_rate

from v_ball
where innings = "2" 
group by batter
having balls > 500
order by strike_rate desc
limit 10;
""")

            batter  balls  runs  strike_rate
0        SP Narine    507   869       171.40
1       AD Russell    660  1130       171.21
2  Abhishek Sharma    648  1108       170.99
3         N Pooran    729  1218       167.08
4         V Sehwag    869  1427       164.21
5       GJ Maxwell    734  1164       158.58
6   P Simran Singh    527   832       157.87
7       JC Buttler   1461  2289       156.67
8      YBK Jaiswal    875  1351       154.40
9         SA Yadav   1382  2131       154.20

In [74]:
q("""
  --which batters are hardest to bowl a dot ball to in the death overs

  
SELECT 
    batter,
    COUNT(*) AS total_balls,
    SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) AS dot_balls,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS dot_ball_percentage
FROM v_ball
WHERE phase = 'Death'
  AND is_legal = 1
GROUP BY batter
HAVING total_balls > 500
ORDER BY dot_ball_percentage ASC
LIMIT 10;
""")

           batter  total_balls  dot_balls  dot_ball_percentage
0       JP Duminy          516        104                20.16
1  AB de Villiers          829        175                21.11
2        SK Raina          521        111                21.31
3        KL Rahul          502        110                21.91
4         V Kohli          807        185                22.92
5        DJ Bravo          516        128                24.81
6       AT Rayudu          692        173                25.00
7       DA Miller          835        212                25.39
8        AR Patel          629        162                25.76
9       RA Jadeja         1240        323                26.05

In [75]:
q("""
--How do runs and wickets differ across the three phases of an innings

SELECT
    phase,
    SUM(total_runs) AS runs,
    SUM(is_wicket) AS wickets,
    round(6.0*sum(total_runs)/sum(is_legal),2) as runs_per_over,
    round(100.0*sum(is_wicket)/sum(is_legal),2)as wicket_perc
FROM v_ball
GROUP BY phase
ORDER BY phase desc;""")

       phase    runs  wickets  runs_per_over  wicket_perc
0  Powerplay  116397     3483           8.03         4.01
1     Middle  169160     5562           7.92         4.34
2      Death  104056     5264          10.04         8.46

In [76]:
q("""
  -- which over of the innings is the most expensive?
  
select
     Over_number+1 as over,
     round(6.0*sum(total_runs)/sum(is_legal),2) as runs_per_over
from v_ball
group by Over_number
order by runs_per_over desc;""")

    over  runs_per_over
0     20          11.39
1     19          10.53
2     18          10.12
3     17           9.46
4     16           9.05
5     15           8.74
6      6           8.68
7      5           8.65
8      4           8.63
9     14           8.43
10     3           8.37
11    13           8.17
12    12           8.13
13    11           7.96
14     9           7.77
15    10           7.66
16     2           7.60
17     8           7.47
18     7           6.98
19     1           6.28

In [77]:
q("""
 -- what is the average score at the end of the powerplay?

select round(AVG(pp_runs),2)as avg_powerplay_Score
from (select match_id, innings, sum(total_runs) as pp_runs
   from v_ball
   where phase = 'Powerplay' and innings in(1,2)
   group by match_id, innings);""")

   avg_powerplay_Score
0                48.14

In [78]:
q("""
-- which over sees the most wickests fall 

select 
over_number+1 as Over,
 SUM(is_wicket) AS wickets

from v_ball
group by Over_number
order by wickets desc;""")

    Over  wickets
0     20     1433
1     19     1089
2     18     1055
3     17      863
4     16      824
5     15      764
6     14      703
7     13      661
8      5      640
9     11      635
10    12      621
11     3      606
12     4      597
13     9      593
14     6      585
15     2      567
16    10      554
17     8      534
18     7      497
19     1      488

In [79]:
q("""
--How many runs are scored in the last over compared with the first?
select 
    Over_number,
    round(6.0*sum(total_runs)/sum(is_legal),2) as runs_per_over
from v_ball
where innings in(1,2)

    


""")

   over_number  runs_per_over
0            0           8.43

In [80]:
q("""
-- The team want the all time leading wicket takers.

select 
   bowler,
   sum(bowler_wicket) as wicket_taken
from V_ball
group by bowler
order by wicket_taken desc;

""")

               bowler  wicket_taken
0           YS Chahal           228
1             B Kumar           215
2           SP Narine           199
3           PP Chawla           192
4            R Ashwin           187
..                ...           ...
563       Tilak Varma             0
564       VS Yeligati             0
565    Vivrant Sharma             0
566  Y Gnaneswara Rao             0
567       YBK Jaiswal             0

[568 rows x 2 columns]

In [81]:
q("""
--who is the most economical bowler, counting only runs that were their fault?
select
    bowler,
    sum(is_legal) as balls,
    round(6.0* sum(bowler_runs)/ sum(is_legal),2)as econamy_rate

from v_ball
group by bowler
having balls>500
order by econamy_rate asc;

""")

             bowler  balls  econamy_rate
0          A Kumble    965          6.58
1    M Muralitharan   1524          6.68
2        DL Vettori    777          6.79
3         SP Narine   4507          6.79
4          DW Steyn   2176          6.92
..              ...    ...           ...
144       SM Curran   1253          9.74
145      MP Stoinis    900          9.85
146    Kartik Tyagi    584         10.00
147    TU Deshpande   1061         10.02
148    Mukesh Kumar    786         10.51

[149 rows x 3 columns]

In [82]:
q("""
-- which bowler takes a wicket most often - best strike rate in balls per wicket?
select
     bowler,
     sum(is_legal) as total_ball,
     sum(bowler_wicket) total_wicket,
     round(sum(is_legal)/sum(bowler_wicket),2) as balls_per_wicket
from v_ball
group by bowler
having total_wicket>50
order by balls_per_wicket asc;

""")

          bowler  total_ball  total_wicket  balls_per_wicket
0     AD Russell        1806           123              14.0
1   JR Hazlewood        1008            65              15.0
2       K Rabada        2112           133              15.0
3       MA Starc        1083            68              15.0
4       HV Patel        2470           151              16.0
..           ...         ...           ...               ...
73     IK Pathan        2043            80              25.0
74     KH Pandya        2560           102              25.0
75      R Ashwin        4710           187              25.0
76     JH Kallis        1742            65              26.0
77       P Kumar        2524            90              28.0

[78 rows x 4 columns]

In [83]:
q("""
-- Which bowler gives away the fewest boundaries?

SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(CASE WHEN batter_runs IN (4, 6) THEN 1 ELSE 0 END) AS boundaries,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs IN (4, 6) THEN 1 ELSE 0 END)
        / SUM(is_legal),
        2
    ) AS boundary_perc
FROM v_ball
WHERE is_legal = 1
GROUP BY bowler
HAVING balls > 500
ORDER BY boundary_perc ASC
LIMIT 10;
""")

           bowler  balls  boundaries  boundary_perc
0        A Kumble    965         106          10.98
1  M Muralitharan   1524         170          11.15
2        R Bhatia   1636         188          11.49
3    Yuvraj Singh    869         100          11.51
4       SP Narine   4507         526          11.67
5      DL Vettori    777          91          11.71
6          MM Ali    854         100          11.71
7        R Ashwin   4710         554          11.76
8        M Kartik   1149         138          12.01
9         J Botha    694          84          12.10

In [84]:
q("""
-- which bowler has the best dot-ball rate at the death?
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(CASE WHEN is_legal = 1 AND total_runs = 0 THEN 1 ELSE 0 END) AS dot_balls,
    ROUND(
        100.0 * SUM(CASE WHEN is_legal = 1 AND total_runs = 0 THEN 1 ELSE 0 END)
        / SUM(is_legal),
        2
    ) AS dot_perc
FROM v_ball
WHERE phase = 'Death'
GROUP BY bowler
HAVING SUM(is_legal) >= 300
ORDER BY dot_perc DESC
LIMIT 10;
""")

              bowler  balls  dot_balls  dot_perc
0          SP Narine   1075        397     36.93
1           CV Varun    310        112     36.13
2         MG Johnson    302        108     35.76
3        Rashid Khan    594        208     35.02
4           DW Steyn    634        218     34.38
5          PP Chawla    444        150     33.78
6           K Rabada    660        222     33.64
7  M Prasidh Krishna    542        182     33.58
8           A Mishra    521        167     32.05
9           MA Starc    333        106     31.83

In [85]:
run_sql_file(r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\08_matches_clean.sql")

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\08_matches_clean.sql

In [86]:
q(""" select count(*) from matches_clean;""")

   count(*)
0      1212