In [14]:
import sqlite3
import pandas as pd

con=sqlite3.connect(r'C:\Users\muham\OneDrive\Desktop\Proj_3.1\Data\Raw\ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [15]:
def run_sql_file(path):
    with open(path,'r') as f:
        script =f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [16]:
q("""
    -- what is the strike rate of every batter in the death overs

    select batter,round(100.0*sum(batter_runs)/sum(
      CASE
        when is_wide_ball=0 AND is_no_ball=0
        then 1
        else 0
      END ),2)as strike_rate

from deliveries
where over_number>=15 AND is_super_over=0
group by batter
order by strike_rate desc;
    """)

             batter  strike_rate
0          WG Jacks       483.33
1          DT Patil       400.00
2        KT Maphaka       400.00
3            L Wood       300.00
4          PA Reddy       300.00
..              ...          ...
637     Sunny Gupta         0.00
638          U Kaul         0.00
639  V Pratap Singh         0.00
640   Y Prithvi Raj         0.00
641      YA Abdulla         0.00

[642 rows x 2 columns]

In [17]:
run_sql_file(r'C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\09_analysis_views.sql')

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\09_analysis_views.sql

In [18]:
q(""" select *
from v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [19]:
q("""select phase, count(*) from v_ball group by phase;""")

       phase  count(*)
0      Death     65488
1     Middle    132173
2  Powerplay     90390

In [23]:
q("""select count(*) from v_match_totals;""")

DatabaseError: Execution failed on sql 'select count(*) from v_match_totals;': no such table: v_match_totals

In [21]:
q("""select count(*) from v_innings;""")

   count(*)
0      2418

In [22]:
q(""" select phase, count(*) from v_ball;""")

       phase  count(*)
0  Powerplay    288051