In [1]:
import sqlite3
import pandas as pd

con = sqlite3.connect(r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\Data\Raw\ipl.db")

def q(sql):
    return pd.read_sql(sql, con)

In [2]:
q("""select * from matches ;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [3]:
q(""" select * from deliveries ;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,1,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,0,0,None,0,2,252,134,Delhi Capitals,Rajasthan Royals
288222,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,0,0,None,0,2,252,134,Delhi Capitals,Rajasthan Royals
288223,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,0,0,None,0,2,252,134,Delhi Capitals,Rajasthan Royals
288224,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,0,0,None,0,2,252,134,Delhi Capitals,Rajasthan Royals
288225,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,0,0,None,0,2,252,134,Delhi Capitals,Rajasthan Royals

In [4]:
q(""" SELECT m.match_id,m.venue,v.city from matches m
JOIN venues v on m.venue = v.venue limit 10 ;""")

   match_id                                      venue       city
0    335982                      M Chinnaswamy Stadium  Bangalore
1   1082591  Rajiv Gandhi International Stadium, Uppal  Hyderabad
2   1082592    Maharashtra Cricket Association Stadium       Pune
3   1082593     Saurashtra Cricket Association Stadium     Rajkot
4   1082594                     Holkar Cricket Stadium     Indore
5   1082595                      M.Chinnaswamy Stadium  Bengaluru
6   1082596  Rajiv Gandhi International Stadium, Uppal  Hyderabad
7   1082597                           Wankhede Stadium     Mumbai
8   1082598                     Holkar Cricket Stadium     Indore
9   1082599    Maharashtra Cricket Association Stadium       Pune

In [5]:
q("""select d.batter,p.bat_style,p.player_full_name from deliveries d join
 players p on d.batter = p.player_name;""")

            batter       bat_style          player_full_name
0       MN Samuels  Right hand Bat  Marlon Nathaniel Samuels
1       MN Samuels  Right hand Bat  Marlon Nathaniel Samuels
2       MN Samuels  Right hand Bat  Marlon Nathaniel Samuels
3       MN Samuels  Right hand Bat  Marlon Nathaniel Samuels
4       MN Samuels  Right hand Bat  Marlon Nathaniel Samuels
...            ...             ...                       ...
288221      N Rana   Left hand Bat               Nitish Rana
288222      N Rana   Left hand Bat               Nitish Rana
288223      N Rana   Left hand Bat               Nitish Rana
288224   SU Parakh   Left hand Bat        Sahil Ulhas Parakh
288225   SU Parakh   Left hand Bat        Sahil Ulhas Parakh

[288226 rows x 3 columns]

In [6]:
q(""" select venue from venues 
except select distinct venue from matches;""")

Empty DataFrame
Columns: [venue]
Index: []

In [7]:
q("""select match_id,innings,over_number,ball_number,count(*) as n
from deliveries
group by match_id,innings,over_number,ball_number;""")

        match_id  innings  over_number  ball_number  n
0         335982        1            0            0  1
1         335982        1            0            1  1
2         335982        1            0            2  1
3         335982        1            0            3  1
4         335982        1            0            4  1
...          ...      ...          ...          ... ..
288221   1529286        2           18            3  1
288222   1529286        2           18            4  1
288223   1529286        2           18            5  1
288224   1529286        2           19            0  1
288225   1529286        2           19            1  1

[288226 rows x 5 columns]

In [8]:
q("""select count(distinct batter)
from deliveries
where batter not in (select player_name from players);""")

   count(distinct batter)
0                       0

In [9]:
q("""select count(*) as total,
sum(case when city is null then 1 else 0 end)as missing
from matches;""")

   total  missing
0   1212       51

In [10]:
q("""select count(*)as total,
sum(case when city is null then 1 else 0 end) as missing 
from venues;""")

   total  missing
0     63        2

In [11]:
q("""select count(distinct venue) as venues
from matches;""")

   venues
0      59

In [12]:
q("""select count(*) as total,
sum(case when city is null then 1 else 0 end)as as_null,
sum(case when city = '' then 1 else 0 end) as empty,
sum(case  when trim(city)= '' and city = '' then 1 else 0 end) as spaces
from matches;""")

   total  as_null  empty  spaces
0   1212       51      0       0

In [13]:
q("""
     select count(distinct
           
           case when instr(venue,',')>0
           then trim(substr(venue,1,instr(venue,',')-1))
        else trim (venue)end) as after_coma
        from matches;""")

   after_coma
0          42

In [14]:
q(""" select count(*)as rows,
count(distinct venue) as distinct_venues
from venues;""")

   rows  distinct_venues
0    63               59

In [15]:
q(""" select venue, count(*) as n
from venues
group by venue
having count(*)>1;""")

                                               venue  n
0                 Dr DY Patil Sports Academy, Mumbai  2
1                Dubai International Cricket Stadium  2
2  Maharaja Yadavindra Singh International Cricke...  2
3                            Sharjah Cricket Stadium  2

In [16]:
q(""" select team_name,
(select count(*)
from matches m
where m.team1=t.team_name or m.team2=t.team_name) as played
from teams t
order by team_name;"""  )

                      team_name  played
0           Chennai Super Kings     260
1               Deccan Chargers       0
2                Delhi Capitals     276
3                 Gujarat Lions      30
4                Gujarat Titans      69
5          Kochi Tuskers Kerala      14
6         Kolkata Knight Riders     272
7          Lucknow Super Giants      66
8                Mumbai Indians     285
9                 Pune Warriors      46
10                 Punjab Kings     272
11             Rajasthan Royals     245
12       Rising Pune Supergiant      30
13      Rising Pune Supergiants       0
14  Royal Challengers Bangalore     279
15          Sunrisers Hyderabad     280

In [17]:
q(""" select result,count(*) as n
from matches
group by result;""")

      result     n
0  no result     9
1        tie    16
2        win  1187

In [18]:
q(""" select match_id, season, result, match_winner
from matches where result = 'no result' and match_winner is not null;""")

   match_id season     result           match_winner
0   1178424   2019  no result       Rajasthan Royals
1   1359519   2023  no result    Chennai Super Kings
2    501265   2011  no result          Pune Warriors
3    829763   2015  no result       Rajasthan Royals
4    829813   2015  no result         Delhi Capitals
5   1473481   2025  no result  Kolkata Knight Riders
6   1473492   2025  no result    Sunrisers Hyderabad
7   1473495   2025  no result         Delhi Capitals
8   1527685   2026  no result           Punjab Kings